-- Migration: add_accounts
--
-- Adds multi-account support so each Position lot can be tracked under a
-- specific Wealthsimple sub-account (TFSA / RRSP / Personal / etc).
--
-- This file was generated by `prisma migrate diff` and then hand-edited to be
-- safe on a populated table:
--   1. Add Position.accountId as NULLABLE
--   2. Seed a default Personal account
--   3. Backfill all existing Position rows to it
--   4. Promote accountId to NOT NULL
--   5. Wire the FK, drop the old unique-on-ticker index, add the composite
-- Without the backfill step Prisma's straight `ADD COLUMN ... NOT NULL`
-- would fail on the 5 existing positions.

-- CreateEnum
CREATE TYPE "AccountType" AS ENUM ('TFSA', 'RRSP', 'SpousalRRSP', 'RESP', 'LIRA', 'RRIF', 'Personal', 'Margin', 'Corporate');

-- CreateTable
CREATE TABLE "Account" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "type" "AccountType" NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'CAD',
    "broker" TEXT NOT NULL DEFAULT 'Wealthsimple',
    "contributionRoomCad" DECIMAL(65,30),
    "archivedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Account_name_key" ON "Account"("name");

-- CreateIndex
CREATE INDEX "Account_type_idx" ON "Account"("type");

-- CreateIndex
CREATE INDEX "Account_archivedAt_idx" ON "Account"("archivedAt");

-- Step 1: add accountId NULLABLE so the populated Position table survives.
ALTER TABLE "Position" ADD COLUMN "accountId" INTEGER;

-- Step 2: seed default account that will own all pre-existing positions.
INSERT INTO "Account" ("name", "type", "currency", "broker", "createdAt", "updatedAt")
VALUES ('Personal (default)', 'Personal', 'CAD', 'Wealthsimple', NOW(), NOW());

-- Step 3: backfill existing positions onto the default account.
UPDATE "Position"
SET "accountId" = (SELECT id FROM "Account" WHERE name = 'Personal (default)')
WHERE "accountId" IS NULL;

-- Step 4: now safe to enforce NOT NULL.
ALTER TABLE "Position" ALTER COLUMN "accountId" SET NOT NULL;

-- Step 5: foreign key + index changes.
ALTER TABLE "Position" ADD CONSTRAINT "Position_accountId_fkey"
  FOREIGN KEY ("accountId") REFERENCES "Account"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

-- Old single-column uniqueness on ticker is replaced by the (accountId, ticker)
-- composite — same ticker is now allowed across different accounts.
DROP INDEX "Position_ticker_key";
CREATE UNIQUE INDEX "Position_accountId_ticker_key" ON "Position"("accountId", "ticker");
CREATE INDEX "Position_accountId_idx" ON "Position"("accountId");
